COMPILER_BASE    = "${COMPILER_ROOT}/${COMPILER_VERSION}/${COMPILER_VERSION}/x-tools/${CURRENT_TARGET}"
COMPILER_PREFIX  = "${CURRENT_TARGET}-"
COMPILER_SYSROOT = "${COMPILER_BASE}/${CURRENT_TARGET}"
C_COMPILER       = "${COMPILER_BASE}/bin/${COMPILER_PREFIX}sysroot_gcc"
CXX_COMPILER     = "${COMPILER_BASE}/bin/${COMPILER_PREFIX}sysroot_g++"
CC_PREFIX_NAME   = "${CURRENT_TARGET}"
CC_PREFIX        = "${COMPILER_BASE}/bin/${COMPILER_PREFIX}"

